-- Crear tables per PostgreSQL

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    email_verified_at TIMESTAMP NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pelis (
    id SERIAL PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    titol VARCHAR(255) NOT NULL,
    descripcio TEXT NOT NULL,
    imatge_url VARCHAR(255) NOT NULL,
    durada_minuts INT NOT NULL,
    estat VARCHAR(20) DEFAULT 'actiu' CHECK (estat IN ('actiu', 'inactiu')),
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    capacitat INT NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories_seients (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    color_hex VARCHAR(7) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
    id SERIAL PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    esdeveniment_id INT NOT NULL REFERENCES pelis(id) ON DELETE CASCADE,
    sala_id INT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    data_hora TIMESTAMP NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS seients (
    id SERIAL PRIMARY KEY,
    sala_id INT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    fila VARCHAR(10) NOT NULL,
    numero INT NOT NULL,
    categoria_id INT NOT NULL REFERENCES categories_seients(id) ON DELETE CASCADE,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS preus_sessio (
    id SERIAL PRIMARY KEY,
    sessio_id INT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    categoria_id INT NOT NULL REFERENCES categories_seients(id) ON DELETE CASCADE,
    preu DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reserves_temporals (
    id SERIAL PRIMARY KEY,
    seient_id INT NOT NULL REFERENCES seients(id) ON DELETE CASCADE,
    sessio_id INT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    usuari_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (seient_id, sessio_id)
);

CREATE TABLE IF NOT EXISTS compres_entrades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuari_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sessio_id INT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    seient_id INT NOT NULL REFERENCES seients(id) ON DELETE CASCADE,
    preu_pagat DECIMAL(10, 2) NOT NULL,
    data_compra TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
