-- Dades inicials de exemple

-- Users de test
INSERT INTO users (id, name, email, password, email_verified_at, created_at, updated_at) VALUES
('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Usuari Test', 'test@example.com', '$2y$12$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- Categories de seients
INSERT INTO categories_seients (nom, color_hex, created_at, updated_at) VALUES
('VIP', '#FFD700', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Platea', '#4169E1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('General', '#228B22', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- Sales
INSERT INTO sales (nom, capacitat, created_at, updated_at) VALUES
('Sala Principal', 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sala Petita', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- Seients Sala Principal (3 files x 10 seients)
INSERT INTO seients (sala_id, fila, numero, categoria_id, created_at, updated_at) VALUES
(1, 'A', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 4, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 5, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 6, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 7, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 8, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 9, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'A', 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'B', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 4, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 5, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 6, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 7, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 8, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 9, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'B', 10, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 'C', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 3, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 5, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 6, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 7, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 8, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 9, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 'C', 10, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- Esdeveniments
INSERT INTO esdeveniments (uuid, titol, descripcio, imatge_url, durada_minuts, estat, created_at, updated_at) VALUES
('b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a12', 'Concert de Rock', 'Un concert increible amb els millors grups', 'https://example.com/rock.jpg', 120, 'actiu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a13', 'Obra de Teatre', 'Una obra de teatre klasik', 'https://example.com/teatre.jpg', 90, 'actiu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (uuid) DO NOTHING;

-- Sessions
INSERT INTO sessions (uuid, esdeveniment_id, sala_id, data_hora, created_at, updated_at) VALUES
('d3eebc99-9c0b-4ef8-bb6d-6bb9bd380a14', 1, 1, '2026-04-01 20:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('e4eebc99-9c0b-4ef8-bb6d-6bb9bd380a15', 1, 1, '2026-04-02 22:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('f5eebc99-9c0b-4ef8-bb6d-6bb9bd380a16', 2, 2, '2026-04-03 19:00:00', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (uuid) DO NOTHING;

-- Preus per sessio
INSERT INTO preus_sessio (sessio_id, categoria_id, preu, created_at, updated_at) VALUES
(1, 1, 50.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 2, 35.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (1, 3, 20.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 50.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (2, 2, 35.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (2, 3, 20.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 40.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (3, 2, 25.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (3, 3, 15.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
